### ISSUE TITLE
Add visualization from model file

### ISSUE THREAD

**Issue by andreasntr** [viscom-ulm/Net2Vis#20]
**Describe the request**
Let the user upload his/her model instead of pasting the entire code

**How can it be tackled?**
For tensorflow, use `tf.keras.models.load_model(h5_file)`

**Comment by Sparkier** [comment]
Thank you for taking the time to submit this feature request. Sadly, I currently don't have the time to implement new features. I hope to be able to do that in October. If you would like to make a PR yourself, I could help you with some pointers as to where to add code.

**Comment by andreasntr** [comment]
> 
> 
> If you would like to make a PR yourself, I could help you with some pointers as to where to add code.

Sure, I can try

**Comment by Sparkier** [comment]
Ok, so I think somewhere here: https://github.com/viscom-ulm/Net2Vis/blob/bf599a9e9b94e705b97f0a40eb26c9be430190dc/net2vis/src/components/code/CodeComponent.js#L71-L79, you might want to add a button for the file upload.

Then the next step would be sending that network to the backend, using a function like this: https://github.com/viscom-ulm/Net2Vis/blob/bf599a9e9b94e705b97f0a40eb26c9be430190dc/net2vis/src/api/CodeApi.js#L21-L26 or augmenting it to also take a network file. Same with its counterpart on the backend side: https://github.com/viscom-ulm/Net2Vis/blob/bf599a9e9b94e705b97f0a40eb26c9be430190dc/backend/server.py#L179-L193

And then for processing the data in the backend, this is the function that returns the network: https://github.com/viscom-ulm/Net2Vis/blob/bf599a9e9b94e705b97f0a40eb26c9be430190dc/backend/server.py#L141-L159
This would need to take into account that maybe you don't have a python file with code but a h5 file.

Finally, for extracting the json network representation, you would need something like this: https://github.com/viscom-ulm/Net2Vis/blob/bf599a9e9b94e705b97f0a40eb26c9be430190dc/backend/translate/translate_keras.py#L9-L28 which starts a docker container for security, then loads in the model file and returns the json representation for the model.

**Comment by andreasntr** [comment]
Actually I thought it would only be a matter of editing Python code, I'm not good with js so I'm not able to update the frontend part

**Comment by Sparkier** [comment]
Oh, that is totally fine. If you still want to look at implementing thy backend part, which is in python, that would already be a big help. I could then add what's missing to the UI.

**Comment by Sparkier** [comment]
Thank you for your contribution. It should now be possible on develop (https://github.com/viscom-ulm/Net2Vis/tree/develop) to upload model files.
I did not merge this yet or deploy as I want to test some more, but don't have time for that this weekend. If you want to try it out, you need to follow the local installation guide as described in the [README](https://github.com/viscom-ulm/Net2Vis/blob/master/README.md) (should be pretty straight forward).

**Comment by andreasntr** [comment]
Unfortunately I can't run docker under Windows10 Home and it's a big mess to use it under WSL2. I'll wait for your additional tests to be done. Thanks again for the effort
