### ISSUE TITLE
URL fetch for pertrained model

### ISSUE THREAD

**Issue by Gpetrak** [viscom-ulm/Net2Vis#28]
Hello Net2Vis developers and congrats for the great work.
I'm trying to visualize an encoder-decoder network in which the encoder is a pre-trained MobileNetV2.
When I import
    
`from tensorflow.python.keras.applications import MobileNetV2`

and update the code, it raises the following error:
Exception: URL fetch failure on "https://https://storage.googleapis.com/tensorflow/keras-applications/mobilenet_v2/mobilenet_v2_weights_tf_dim_ordering_tf_kernels_0.35_224_no_top.h5" : None [Errno -3] Temporary failure in name resolution

I think that it is a strict-origin-when-cross-origin bug but I'm not a React user in order to solve the issue.

Any suggestions ?

**Comment by Sparkier** [comment]
Thank you for reporting this. I am investigating.

**Comment by Sparkier** [comment]
As it seems, this is not an issue with React. When you instantiate MobileNetV2, it tries to fetch a weight file inside the docker container that is started in the backend once you update the code.

This is not really desirable as you do not need the weights to visualize the network, it will make the container run much longer as each time the container starts it needs to download the weights, and it will pollute the server. Thus, I am not going to enable loading weights for now.

To make Net2Vis work with your network, you can set `weights=None`. See [this example](https://viscom.net2vis.uni-ulm.de/uRhctCopTc17BNMQ6w3CI1AOarHa06P5FEuEAdylcK2i1mgaWr).

**Comment by Gpetrak** [comment]
You are absolutely right ! Thank you for your answer and the example.
