### ISSUE TITLE
Support of custom layers

### ISSUE THREAD

**Issue by sraimund** [viscom-ulm/Net2Vis#37]
Hi, what a nice and practical tool!

I'm wondering if you support [subclassed layers](https://keras.io/guides/making_new_layers_and_models_via_subclassing/)? I tried:

```python
from keras.layers import Layer
from keras import Input, Model
from keras.utils import custom_object_scope, get_custom_objects

class CustomLayer(Layer):
    def call(self, x):
        return x + 1.

def get_model():
    x = Input(1)
    custom_layer = CustomLayer()(x)
    model = Model(inputs=x, outputs=custom_layer)

    config = model.get_config()
    custom_objects = {"CustomLayer": CustomLayer}
    
    # this does not help
    with custom_object_scope(custom_objects):
        new_model = Model.from_config(config)
        return new_model

    # this also does not help
    get_custom_objects().update(custom_objects)
    return model
```
The error message "Unknown layer: CustomLayer. Please ensure this object is passed to the `custom_objects` argument. See https://www.tensorflow.org/guide/keras/save_and_serialize#registering_the_custom_object for details." is returned in both cases.

Is there a way to make it work?

**Comment by Sparkier** [comment]
Sadly, I think there is no way to make this work. To make a custom layer work here, you would need to pass it, e.g. here:

https://github.com/viscom-ulm/Net2Vis/blob/b60e2afe25408f51981fa6b0841644f95c8b0c6e/backend/translate/translate_keras.py#L60

However, we do not have access to the `CustomLayer` at this point as it is part of the user code. We only execute the user code in a Docker container to make sure malicious code cannot be run on our server directly. Then, we hand over only the model json to load that in our server code. See:

https://github.com/viscom-ulm/Net2Vis/blob/b60e2afe25408f51981fa6b0841644f95c8b0c6e/backend/translate/translate_keras.py#L50-L56

and:

https://github.com/viscom-ulm/Net2Vis/blob/b60e2afe25408f51981fa6b0841644f95c8b0c6e/backend/translate/keras_loader.txt#L1-L4

Thus, there is not really a safe way to access these custom Layers.

As I don't know of a general way to make this work, I will close this issue for now. Feel free to reopen it if you have an idea or further suggestion. For now, the easiest solution would be to clone the repo, remove the epicbox code and directly load your model in the server (assuming the code sent from the frontend is safe). Then you could access the custom layer.
