### ISSUE TITLE
Issue with grouping layers

### ISSUE THREAD

**Issue by sjherzog** [viscom-ulm/Net2Vis#4]
Thanks for the great work, 

but i have a problem with the grouping, if I group two layers and then click on update the layers are grouped into one block, but if I then click on the grouped block the web page turns complete white.

Eg: ![screen1](https://user-images.githubusercontent.com/31650382/75348988-24975600-58a4-11ea-8bfa-fc29215f2ba2.png)

output:

![screen3](https://user-images.githubusercontent.com/31650382/75349743-a89e0d80-58a5-11ea-8938-40436cf19078.png)

A network id where it would have happened:

X1648BngMHlDdToFMFD254FpL5flX491eJnnO3tWBLMlxNWyxI

 - OS: Arch Linux 5.5.5-arch1-1
 - Browser Firefox
 - Version 73.0.1 (64-bit)

I have also tried to run Net2Vis in a VM, you get the same error. But instead of the white browser window you get the error

![screen3](https://user-images.githubusercontent.com/31650382/75349467-201f6d00-58a5-11ea-887b-692c0c0c943c.png)

Greeetings

**Comment by Sparkier** [comment]
Thank you for pointing this out. I introduced a bug with a minor refactoring. This should be fixed now.
