### ISSUE TITLE
Layers are not showed

### ISSUE THREAD

**Issue by mcapurso** [viscom-ulm/Net2Vis#49]
**Describe the bug**
The Dense, Dropout and Flatten layers are not showed

**Network ID**
sjPFe7YWegLrcIQzlIZYbQAL1QmqmyWtJSlOKuSapOTyrMOSiB

**Expected behavior**
Layers shoud be showed

**Screenshots**
Follows below

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 LTS
 - Browser [e.g. chrome, safari] Mozilla Firefox 
 - Version [e.g. 22] 121.0
![copertina](https://user-images.githubusercontent.com/8177173/235464352-ceb4f0d9-7ac9-4077-8b84-60482786d4dd.png)
[prova.txt](https://github.com/viscom-ulm/Net2Vis/files/11365795/prova.txt)

**Additional context**
The python code follows, under the name prova.txt

**Comment by Sparkier** [comment]
Hi @mcapurso, thank you for the feedback. This was an error with the configuration you passed to Net2Vis. If you change:
```model = models.Model(img_input, pool2)```
to 
```model = models.Model(img_input, dense1)```
in line 23, everything works as expected.
