### ISSUE TITLE
Squeeze layer giving error

### ISSUE THREAD

**Issue by drahcirD** [viscom-ulm/Net2Vis#5]
**Describe the bug**
I use a tf.squeeze layer in my network. I could not make tf.squeeze work with net2vis and a lambda layer did not work either.  tf.squeeze gives me the error 'NoneType' object has no attribute _inbound_nodes and wrapping keras.backend.squeeze in a lambda layer says that squeeze is not JSON serializable.

**Network ID**
https://viscom.net2vis.uni-ulm.de/7fplsc22NA6oYhvyr6BAy80XODOK4oP1gB7tR8sTygh9iw1Npd

**Expected behavior**
I want to visualize a model starting with Conv3D then squeeze, then conv2d.

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser chrome
 - Version 80

**Comment by Sparkier** [comment]
Thank you for pointing this out. The first option does not work as you can only serialize Keras Layers, which is what we are doing.

The second option does not work, as when deserializing, it does not know what squeeze stands for, see [this issue](https://github.com/keras-team/keras/issues/5298).

I am trying to find a fix, but have not been successful so far.

**Comment by Sparkier** [comment]
Closing this as I was not able to find a fix. Feel free to reopen if neccessary.
