### ISSUE TITLE
Example model not working

### ISSUE THREAD

**Issue by AndersonMonken** [viscom-ulm/Net2Vis#7]
**Describe the bug**
When just opening the site and clicking update so I can see the base example model, a popup that says "code is not executable" shows up. I cannot get any output at all.

**Network ID**
https://viscom.net2vis.uni-ulm.de/m3Xmi4QXgEHJTcnSawGjQChWhOwKhcEBQzaw0gWHnWIMlDmN15

**Expected behavior**
The site to work. I was really excited about it :)

**Screenshots**
NA. I tried on multiple machines on the base code and get the same error each time.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 83.0

**Additional context**
Thanks!

**Comment by Sparkier** [comment]
Hey, thank you for reporting this. Somehow our docker deamon for the backend was down, sorry for that. Your network should work now without any problem.

Let me know if you run into any more problems.
